/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.inventory;

/**
 *
 * @author Andrew
 */
public class AddItemConfirmationGUI extends javax.swing.JFrame {

//    private String itemName;
//    private int itemBarcode;
//    private int itemQty;
//    private float itemPrice;
    /**
     * Creates new form AddItemConfirmationGUI
     *
     */
    public AddItemConfirmationGUI(String itemBarcode, String name, float itemPrice, int itemQty) {
        initComponents();
        Name.setText(name);
        barcode.setText(String.valueOf(itemBarcode));
        price.setText(String.valueOf(itemPrice));
        qty.setText(String.valueOf(itemQty));
        
        
    }
    
    public AddItemConfirmationGUI(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        barcode = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 212));
        setSize(new java.awt.Dimension(400, 212));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Item Barcode:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 80, 14);

        jLabel2.setText("Item Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 70, 14);

        jLabel3.setText("Item Price:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 70, 14);

        jLabel4.setText("Item Quantity:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 80, 80, 14);

        barcode.setText("jLabel5");
        jPanel1.add(barcode);
        barcode.setBounds(140, 20, 34, 14);

        Name.setText("jLabel6");
        jPanel1.add(Name);
        Name.setBounds(140, 40, 34, 14);

        price.setText("jLabel7");
        jPanel1.add(price);
        price.setBounds(140, 60, 34, 14);

        qty.setText("jLabel8");
        jPanel1.add(qty);
        qty.setBounds(140, 80, 34, 14);

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm);
        confirm.setBounds(34, 139, 91, 23);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(139, 139, 73, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        this.dispose();
        AddItemGUI newFrame = new AddItemGUI();
        newFrame.setVisible(true);
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        AddItemGUI newFrame = new AddItemGUI();
        newFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItemConfirmationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItemConfirmationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItemConfirmationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItemConfirmationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemConfirmationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel barcode;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel qty;
    // End of variables declaration//GEN-END:variables
}
