/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.inventory;

import javax.swing.JFrame;

/**
 *
 * @author Andrew
 */
public class AddItemGUI extends javax.swing.JFrame {

    DBHelper db = new DBHelper();

    /**
     * Creates new form ItemGUI
     */
    public AddItemGUI() {
        initComponents();
        db.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemBarcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        itemPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 51, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(400, 210));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 250));
        setSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel1.setLayout(null);

        itemBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarcodeActionPerformed(evt);
            }
        });
        itemBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemBarcodeKeyTyped(evt);
            }
        });
        jPanel1.add(itemBarcode);
        itemBarcode.setBounds(130, 60, 210, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Barcode");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 50, 15);

        itemName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        itemName.setEnabled(false);
        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });
        itemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemNameKeyTyped(evt);
            }
        });
        jPanel1.add(itemName);
        itemName.setBounds(130, 90, 210, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Item Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 70, 15);

        itemPrice.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        itemPrice.setEnabled(false);
        itemPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPriceActionPerformed(evt);
            }
        });
        itemPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemPriceKeyTyped(evt);
            }
        });
        jPanel1.add(itemPrice);
        itemPrice.setBounds(130, 120, 210, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 50, 15);

        itemQuantity.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        itemQuantity.setEnabled(false);
        itemQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuantityActionPerformed(evt);
            }
        });
        itemQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemQuantityKeyTyped(evt);
            }
        });
        jPanel1.add(itemQuantity);
        itemQuantity.setBounds(130, 150, 210, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 150, 70, 15);

        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn);
        cancelBtn.setBounds(240, 200, 90, 25);

        addBtn.setText("Add Item");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(130, 200, 90, 25);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrew\\Documents\\NetBeansProjects\\Inventory\\Assets\\add-list.png")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 10, 40, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add To Inventory");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 10, 190, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemBarcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemBarcodeKeyTyped

    }//GEN-LAST:event_itemBarcodeKeyTyped

    private void itemBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarcodeActionPerformed
        System.out.println(itemBarcode.getText());
        itemBarcode.setEnabled(false);
        itemName.setEnabled(true);
        itemName.requestFocus();
        itemPrice.setEnabled(true);
        itemQuantity.setEnabled(true);
    }//GEN-LAST:event_itemBarcodeActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void itemNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameKeyTyped

    private void itemPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPriceActionPerformed

    private void itemPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemPriceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPriceKeyTyped

    private void itemQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQuantityActionPerformed

    private void itemQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemQuantityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQuantityKeyTyped

    //When Add Item Button is pressed
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String barcode = itemBarcode.getText();
        String name = itemName.getText();
        float price = Float.parseFloat(itemPrice.getText());
        int quantity = Integer.valueOf(itemQuantity.getText());

//        adds item to db
//        also checks if it is added successfully
        if (db.addItem(barcode, name, price, quantity)) {
            this.setVisible(false);
            AddItemConfirmationGUI confirmationFrame = new AddItemConfirmationGUI(barcode, name,price,quantity);
            confirmationFrame.setVisible(true);
        } else {
           
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField itemBarcode;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemPrice;
    private javax.swing.JTextField itemQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
